Support open-source solvers (highs, cbc, glpk) with --solver option, but too slow for large MLP

diff --git a/scripts/pantax b/scripts/pantax
--- a/scripts/pantax
+++ b/scripts/pantax
@@ -45,8 +45,9 @@ function print_help() {
   echo "        -lt, --long-read-type str         Long read type (hifi, clr, ontr9, ontr10). Set precise-clipping based on read type."
   echo "        --precise-clipping float          clip the alignment ends with arg as the identity cutoff between correct / wrong alignments. (default: 0.66)"    
   echo "    Abundacnce calculation:"
-  echo "        --species-level                   Species abundance calulation."
-  echo "        --strain-level                    Strain abundance calulation."
+  echo "        --species-level | --species       Species abundance calulation."
+  echo "        --strain-level | --strain         Strain abundance calulation."
+  echo "        --solver str                      MLP solver. (options: gurobi, cbc, glpk, highs. default: gurobi)"
 #   each "        -m, --select                        Select output pangenome result." 
 #   echo "        --parallel-poa                    Parallel POA."
 #   echo "        -ds, --designated_species         Only return the strain result of designated species."
@@ -54,7 +55,8 @@ function print_help() {
   echo "        -a float                          Species with relative abundance above the threshold are used for strain abundance estimation. (default: 0.0001)"
 #   echo "        -fr float                         Unique trio nodes fraction. (default: multi species 0.3/ single species 0.43)"
 #   echo "        -fc float                         Unique trio nodes mean count fraction (default: 0.46)."
-  echo "        -fr float                         The fraction of strain-specific triplet nodes covered by reads for one strain. The larger, the stricter. (default: multi species 0.3/ single species 0.43)"
+  echo "        -fr float                         The fraction of strain-specific triplet nodes covered by reads for one strain. The larger, the stricter." 
+  echo "                                          (default: short multi species 0.3/ short single species 0.43/ long multi species 0.5)"
   echo "        -fc float                         The divergence between first rough and second refined strain abundance estimates. The smaller, the stricter. (default: 0.46)"
   echo "        -sh, --shift bool                 Shifting fraction of strain-specific triplet nodes. (multi-species: off, single-species: on)"
   echo "        -sd float                         Coverage depth difference between the strain and its species, with only one strain. (default: 0.2)"
@@ -119,7 +121,8 @@ parallel_poa="True"
 designated_species=None
 isfilter=1
 species_abund_threshold=0.0001
-default_unique_trio_nodes_fraction=0.3
+default_short_unique_trio_nodes_fraction=0.3
+default_long_unique_trio_nodes_fraction=0.5
 unique_trio_nodes_fraction=None
 default_unique_trio_nodes_count=0.46
 unique_trio_nodes_count=None
@@ -129,7 +132,8 @@ default_single_cov_ratio=0.85
 single_cov_ratio=None
 min_cov=0
 min_depth=0
-gurobi_threads=1
+solver=gurobi
+solver_threads=1
 
 sample_test=0
 sample=500000
@@ -200,8 +204,9 @@ while [[ "$1" != "" ]]; do
         "-lt" | "--long-read-type") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { long_read_type="$2"; shift 2; };;
         "--precise-clipping") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { precise="$2"; shift 2; };;
 
-        "--strain-level") strain_level_flag="True"; shift 1;;
-        "--species-level") species_level_flag="True"; shift 1;;
+        "--strain-level" | "--strain") strain_level_flag="True"; shift 1;;
+        "--species-level" | "--species") species_level_flag="True"; shift 1;;
+        "--solver") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { solver="$2"; shift 2; };;
         "-m" | "--select") select_mode=$2; shift 2;;
         "--parallel-poa") parallel_poa=$2; shift 2;;
         "-ds" | "--designated_species") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { designated_species="$2"; shift 2; } ;;
@@ -217,7 +222,7 @@ while [[ "$1" != "" ]]; do
         "-S" | "--classified-out") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { read_aln="$2".gaf; shift 2; } ;;                                                                          
         "-R" | "--report") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { pantax_report="$2".tsv; shift 2; } ;;
         "-o" | "--output") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { pantax_output=$2; shift 2; } ;;
-        "-gt") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { gurobi_threads=$2; shift 2; } ;;
+        "-gt") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { solver_threads=$2; shift 2; } ;;
         "--sample") [[ -z "$2" ]] && { echo "Error: $1 expects an argument"; exit 1; } || { sample=$2; shift 2; } ;;                                                             
 
         "--sample-test") sample_test=1; shift 1;;
@@ -336,7 +341,7 @@ if [ -z $tmp_dir ]; then
     tmp_dir=$(basename $pantax_db)_tmp
     tmp_dir=$(readlink -f $tmp_dir)
 elif [ ! -z $tmp_dir ] && [ -d $tmp_dir ]; then
-    tmp_dir=$tmp_dir/${pantax_db}_tmp
+    tmp_dir=$tmp_dir/$(basename $pantax_db)_tmp
 elif [ ! -z $tmp_dir ] && [ ! -d $tmp_dir ]; then
     :
 fi
@@ -657,7 +662,11 @@ if [ $unique_trio_nodes_fraction == "None" ] || [ $unique_trio_nodes_count == "N
         if [[ $line_count -eq 1 && $unique_trio_nodes_fraction = "None" ]]; then
             unique_trio_nodes_fraction=0.43
         else
-            unique_trio_nodes_fraction=$default_unique_trio_nodes_fraction
+            if [ $short_reads == "True" ]; then
+                unique_trio_nodes_fraction=$default_short_unique_trio_nodes_fraction
+            elif [ $long_reads == "True" ]; then
+                unique_trio_nodes_fraction=$default_long_unique_trio_nodes_fraction
+            fi
         fi  
     fi 
     if [ $unique_trio_nodes_count == "None" ]; then
@@ -683,6 +692,10 @@ if [ $shift_unique_trio_nodes_fraction == "None" ]; then
     else
         shift_unique_trio_nodes_fraction=""
     fi
+elif [ $shift_unique_trio_nodes_fraction == "False" ] || [ $shift_unique_trio_nodes_fraction == "false" ]; then
+    shift_unique_trio_nodes_fraction=""
+elif [ $shift_unique_trio_nodes_fraction == "True" ] || [ $shift_unique_trio_nodes_fraction == "true" ]; then
+    shift_unique_trio_nodes_fraction="--shift"
 fi
 
 # profiling opt and cmd
@@ -702,7 +715,8 @@ pantaxr_opt="-d $pantax_db -w ./ -m gfa_mapped.gaf \
                 --mode $select_mode \
                 --full \
                 -o ./ \
-                --gthreads $gurobi_threads \
+                --solver $solver \
+                --gthreads $solver_threads \
                 -t $threads \
                 $shift_unique_trio_nodes_fraction $sample_test $save_flag $species_flag $strain_flag $debug_flag"
 $pantaxr profile $pantaxr_opt
